### PR TITLE
feat: add jack parser

### PR DESCRIPTION
**Pull request by henok-tesfaye**
Make progress on #32 

**What kind of change does this PR introduce?**
It's a feature PR which adds a complete jack parser that can handle expressions as well. 

**Does this PR introduce a breaking change?**
No

**What needs to be documented once your changes are merged?**
Nothing

### CODE REVIEW

**Comment by mikereze** [comment]
I don't see why you use the `writer` object. because we won't be generating XML code anymore or did you want it to be part of the simulation?

**Comment by mikereze** [comment]
Where is the symbolTable object? you should do that before jack parser

**Comment by mikereze** [comment]
It would be great if we all follow the API that is recommended in the book. i found it that the API must look like this
api_suggested

**Comment by henok-outlier** [comment]
@mikereze we followed the API used in the book. Did you see anything that opposes the API?

**Comment by mikereze** [comment]
> @mikereze we followed the API used in the book. Did you see anything that opposes the API?

I'm not sure if it is mentioned in the book or not but I saw `eat()` that noam suggested. In addition I didn't saw a command like `tokenizer.back()`.

**Comment by henok-outlier** [comment]
@mikereze that's an implementation instead of an API.

**Comment by mikereze** [comment]
> @mikereze that's an implementation instead of an API.

which one?

**Comment by mikereze** [comment]
tobeChecked2

it is a bit simpler if we use the eat() command so that the code will be concise and simple to read

tobeChecked1

**Comment by henok-tesfaye** [comment]
Screen Shot 2020-11-07 at 3 04 54 PM

@mikereze API is all about the function inputs and its outputs. But you are suggesting to copy paste an already implemented logic.

**Comment by mezzzi** [comment]
> tobeChecked2
> 
> it is a bit simpler if we use the eat() command so that the code will be concise and simple to read
> 
> tobeChecked1

@mikereze good suggestion. But at the end of the day implementation detail will have to be left up to the developer, and @henok-tesfaye is justified to go with his own style of implementation as long as he is meeting the api requirements. And we cannot force him to use the `eat` or the `drink` method, whatever the book authors chose to use as an example.

And given the limited time we have, we shouldn't bother much about following a certain narrow implementation approach, it is enough if we catch obvious errors, or logic flaws, in our reviews.

**Comment by mikereze** [comment]
> Screen Shot 2020-11-07 at 3 04 54 PM
> 
> @mikereze API is all about the function inputs and its outputs. But you are suggesting to copy paste an already implemented logic.

@henok-tesfaye @mezzzi  you are right. everything seems great to me

**Review by mikereze — APPROVED** [review]

**Pull request merged**
