### PR TITLE
feat: add jack tokenizer

### PR DESCRIPTION
**Pull request by henok-tesfaye**
Make progress on #32 

**What kind of change does this PR introduce?**
It's a feature which adds `JackTokenizer` module as the first step for compiler construction.

From the book section 10.3.2, JackTokenizer module.

**Does this PR introduce a breaking change?**
No

**What needs to be documented once your changes are merged?**
Nothing

### CODE REVIEW

**Comment by mezzzi** [comment]
@henok-tesfaye some tests failing, Can this be fixed or am I testing it wrong?
Screenshot from 2020-11-05 20-22-07

**Comment by henok-tesfaye** [comment]
@mezzzi can you try it with latest node version? All tests are passing on my end. My node version is `v14.0.0`.

**Comment by mezzzi** [comment]
@henok-tesfaye you are right it runs fine with v14, as shown below. We need to note this down, so we include it somewhere in the readme.
Screenshot from 2020-11-05 20-29-12

**Review by mezzzi — APPROVED** [review]
Great work: the extensive test cases are awesome!

**Pull request merged**
