### PR TITLE
refactor: make the codebase to follow standard JS conventions

### LINKED ISSUE #8: Make the codebase to follow standard JS conventions
We want our codebase to follow standard JS conventions, https://standardjs.com/.

### PR DESCRIPTION
**Pull request by henites72**
Fixes #8 

I did, `standard --fix` on the base directory, to fix the lint errors.

### CODE REVIEW

**Comment by henites72** [comment]
@Buranch you can install standard globally and run, `standard --fix`. Let me know if this is what you want?

**Comment by Buranch** [comment]
@henites72 yes, but let's not relay on global packages. One of us may not install it. Its good to have on package.json.

**Comment by mezzzi** [comment]
Yes, I agree with @Buranch . Let's add `standard` as a dev dependency (we shouldn't expect devs to install `standard` globally). Also let's have a script that runs standard. It will be run later as part of the build. We can update `package.json` as follows:
```
  "devDependencies": {
    "standard": "*"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject",
    "standard": "standard"
  },
```

**Comment by mezzzi** [comment]
And when I run `npm run standard` I got the following errors:
Screenshot from 2020-02-29 11-33-30
Screenshot from 2020-02-29 11-34-00

**Comment by mezzzi** [comment]
And when I run `npm run standard` I got the following errors:
Screenshot from 2020-02-29 11-33-30
Screenshot from 2020-02-29 11-34-00

**Comment by Buranch** [comment]
@mezzzi did the error got fixed.

**Comment by Buranch** [comment]
@henites72 also if you can add as an admin on the Netlify dashboard we would appreciate it.

**Comment by Buranch** [comment]
@henites72 @mezzzi I've added a fix for the error @mezzzi and I was facing.

**Pull request merged**
